### ISSUE TITLE
Visualize State Space not working with Graphviz

### ISSUE THREAD

**Issue by Thili98** [hhu-stups/prob-issues#100]
I have tried every possible way to connect graphviz with ProB to animate my file. Still Visualize Statespace is not working. 
Nothing appears after clicking View State Space Button
![image](https://user-images.githubusercontent.com/37531486/142927301-32590588-3450-4b39-a0b4-2709a1115595.png)
![image](https://user-images.githubusercontent.com/37531486/142927466-bdbf4e31-0e7e-4202-9249-270d0fa37923.png)

**Comment by leuschel** [comment]
Hi,

what exactly are the symptoms/messages?

Note: you can switch to viewing a PDF generated by the command-line tool dot using the menu command;
Preferences -> Graphical Viewer-> Postscript
This will instruct ProB to first generate a PDF and then call the Postscript/PDF viewer you have selected in the preferences.

A note to macOS users: the only Dot viewer that seems to be working currently is graphviz-gui by MacPorts; see https://prob.hhu.de/w/index.php?title=Download#Graphviz_Requirements.

**Comment by Thili98** [comment]
I have tried connecting dotty.exe from graphviz to ProB animator as in the screenshots.
Correct paths have been added. Then after I clicked View State Space from Visualize menu item, I got nothing appears on my screen.

**Comment by Thili98** [comment]
I also tried PostScript option. It too gives me an error like below. :(
Even though I installed gv it says there is no such file or directory. 
![image](https://user-images.githubusercontent.com/37531486/142985215-70e9ff56-cbf5-49a8-bdca-0b0718c8c607.png)

**Comment by leuschel** [comment]
You have to set the path to the Postscript/PDF viewer by selecting the "Path/Command for Postscript viewer" .exe file. It seems you have selected the Archive (.tar.gz) and not the application.

When using dotty as "Dot Viewer", is something written on the console/terminal? If not, select the Debug -> Debugging Info menu command and try again.

**Comment by scorpionknifes** [comment]
For people still looking to use the PDF viewer on windows. You can install `gv` using cygwin and add `gv` to windows PATH.

**Comment by iTitus** [comment]
Or try to install it natively as explained here: http://graphviz.org/download/
If you don't add your installation to the PATH, make sure that you change your DOT preference to the dot executable.

**Comment by iTitus** [comment]
The errors the user gets to see should be more clear now as well.

**Comment by AndreaPasconcino** [comment]
HI All,

I am detecting the same issue with Dot viewer. Please could you help me to understand in which way it has been solved ?

Note that graphviz version is graphviz-2.44.1-win32.zip

thank you in advance

**Comment by iTitus** [comment]
If you have a .zip or .tar.gz you need to extract it somewhere. The executable is inside the archive.

**Comment by AndreaPasconcino** [comment]
Hi,
yes, I already did so, but when the issue seems not solved, see attached screenshot.
Ies there other setting to be done ? Which one ?

thank you
[dottySetting.docx](https://github.com/hhu-stups/prob-issues/files/11721676/dottySetting.docx)

**Comment by iTitus** [comment]
that is not a screenshot but a docx, please attach an image.

**Comment by npuil** [comment]
![ViewerIssue](https://github.com/hhu-stups/prob-issues/assets/136328872/245ea757-71d0-4d36-8f56-04ce18f8bf01)

**Comment by iTitus** [comment]
It would be helpful if you share any error messages that show up as popups or in the console.

- `dotty` is deprecated and might not exist in your graphviz distribution, make sure it exists.
- If you do not have `dotty` or cannot get it to work, try to use the PostScript/PDF viewer.

**Comment by AndreaPasconcino** [comment]
Hi,

I see dotty.exe, but in order to replace it , please could you tell me where I may find the right excutable for Postscript?

**Comment by iTitus** [comment]
You could use gv or gvedit.
