### ISSUE TITLE
Unhelpful error message when DOT is not installed

### ISSUE THREAD

**Issue by iTitus** [hhu-stups/prob-issues#114]
![image](https://user-images.githubusercontent.com/5154317/162409471-7ffb3881-8e5f-44da-89f7-e3a9d835dff3.png)

Make it more clear for the users that DOT needs to be installed and either...
 - ...  be on the PATH
 - ... or the `DOT` Preference needs to be set to the DOT binary
 
 Maybe use this for inspiration:
![image](https://user-images.githubusercontent.com/5154317/162410636-3a3b178e-e1dc-4378-92ef-227f41a102ff.png)

**Comment by yutak001** [comment]
Issues with the dot path will now be displayed in an alert window.
