### ISSUE TITLE
Save formulas of Graph Visualisation in the Project

### ISSUE THREAD

**Issue by SeeBasTStick** [hhu-stups/prob-issues#133]
It would be nice if one could name and save formulas in the project file for each machine.

**Comment by favu100** [comment]
This is possible now. The next step is about annotating them as validation tasks to use in VOs. Furthermore, they should be manually dischargeable.

**Comment by favu100** [comment]
It is now possible to discharge and fail Visualization VTs. The next step is to integrate the new feature with the TextArea that was removed before

**Comment by favu100** [comment]
Also, it is not possible to discharge/fail visualizations without formula
