### ISSUE TITLE
Allow showing location of machine/trace files in file explorer/Finder

### ISSUE THREAD

**Issue by dgelessus** [hhu-stups/prob-issues#140]
We already have a context menu option to open machines and trace files in an external editor. It should also be possible to reveal the location of the file in the system file browser (File Explorer, Finder, Dolphin, etc.).

**Comment by iTitus** [comment]
Done for trace files

**Comment by iTitus** [comment]
Done for the machines tab.
Maybe do it for the BEditorView as well?
