### ISSUE TITLE
Display model checking options more readably in table

### ISSUE THREAD

**Issue by dgelessus** [hhu-stups/prob-issues#142]
The model checking configurations table currently shows every possible option in a separate table column. This is not very readable, as we now have over 10 different options, most of which aren't used at the same time. As you can see on the screenshot, you have to make the verifications panel/window very wide to see the entire table:

![Model checking table screenshot](https://user-images.githubusercontent.com/6641959/169297247-876b34c9-c552-4a41-925c-a14002365027.png)

It would be better to have only a single column (e. g. "Configuration") that displays a text description of just the options that are actually used. For example:

* \[MC3\] Mixed BF/DF, other errors
* Breadth First, deadlocks, invariant, other errors, goal: door = closed
* \[MC1\] Breadth First, other errors, goal: gear = retracted

Related: #73 would also allow viewing a model checking configuration's options in a more readable format.

**Comment by iTitus** [comment]
![image](https://user-images.githubusercontent.com/5154317/169708479-650eacb4-f9ff-4299-80be-c1c9402e46e7.png)

**Comment by iTitus** [comment]
Still TODO:
 - make the description translatable

**Comment by iTitus** [comment]
Old JSON representation:
```json
      "modelcheckingItems": [
        {
          "nodesLimit": "-",
          "timeLimit": "60",
          "options": {
            "options": [
              "FIND_DEADLOCKS",
              "FIND_INVARIANT_VIOLATIONS",
              "INSPECT_EXISTING_NODES"
            ]
          },
          "goal": "-",
          "shouldExecute": true
        },
        {
          "nodesLimit": "1000000",
          "timeLimit": "-",
          "options": {
            "options": [
              "FIND_INVARIANT_VIOLATIONS",
              "INSPECT_EXISTING_NODES"
            ]
          },
          "goal": "-",
          "shouldExecute": true
        }
      ]
```

NEW JSON representation:
```json
      "modelcheckingItems": [
        {
          "timeLimit": 60,
          "options": [
            "FIND_DEADLOCKS",
            "FIND_INVARIANT_VIOLATIONS",
            "INSPECT_EXISTING_NODES"
          ],
          "shouldExecute": true
        },
        {
          "nodesLimit": 1000000,
          "options": [
            "FIND_INVARIANT_VIOLATIONS",
            "INSPECT_EXISTING_NODES"
          ],
          "shouldExecute": true
        }
      ]
```

**Comment by iTitus** [comment]
Do we want to make the description text translatable or is it some kind of domain language that needs to look like that?

**Comment by dgelessus** [comment]
Ideally the descriptions should be translated, yes. There's no formal DSL for the model checking options, they just need to be human-readable.

**Comment by iTitus** [comment]
Implemented
