### ISSUE TITLE
VisB returns wrong transition IDs

### ISSUE THREAD

**Issue by favu100** [hhu-stups/prob-issues#143]
It seems that VisB returns wrong transition IDs from ProB2 Prolog Interface.
When clicking on the circle for pedestrians green in the Traffic Light model, the cars' traffic light turns red and yellow instead.

[DEBUG] prob2_visb_perform_click(peds_green,[],0,TransIDS),true.
[DEBUG] Yes: TransIDS->[1] 

It it the same transition ID as the one returned when clicking on the circle for cars yellow.

[DEBUG] prob2_visb_perform_click(cars_yellow_1,[],0,TransIDS),true.
[DEBUG] Yes: TransIDS->[1] 

Possibly helpful information: This problem does not appear in an HTML document generated from B2Program.

**Comment by leuschel** [comment]
The issue should be fixed in prob_prolog. The issue was caused by a missing parameter during refactoring.

**Comment by favu100** [comment]
Yes, the issue is fixed now
