### ISSUE TITLE
Show ProB2-UI LTL patterns table only when there are patterns

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#144]
The LTL pane of the ProB2-UI verifications view always contains a LTL patterns table.
In 99 % of cases this table is empty, but takes up a lot of space.
Can we hide the table when it is empty? Or only show it upon demand in an external window?
![Screenshot 2022-05-25 at 10 23 23](https://user-images.githubusercontent.com/1742246/170216503-fe7ad175-7f15-4f30-a361-1e729881e61b.png)

**Comment by SherinSchneider** [comment]
LTL patterns table is now hidden when empty
