### ISSUE TITLE
ProB2-UI FInd Goal model checking - no way to re-execute search

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#148]
I have entered a Find alternate goal model checking task and it found a solution.
I animated and wanted to re-execute the "Find goal" task but double clicking on the entry
in the verifications view had no effect, nor did I find a way by right-clicking to re-execute the task
and navigate the animator to the goal.

**Comment by dgelessus** [comment]
You can right-click on the "Goal found" entry in the bottom table and then select "Show Trace". But you're right that this isn't very discoverable. At least double-clicking on the "Goal found" entry should also work.

<img width="270" alt="Show Trace" src="https://user-images.githubusercontent.com/6641959/172562512-d0f1d199-e73f-4486-bdbf-a2bc1cb6f201.png">

**Comment by leuschel** [comment]
Maybe it would be good also to remove the Index column and disallow sorting.

**Comment by SherinSchneider** [comment]
find goal can now be re-executed via double click, button and the already described way with context menu. Additionally index column was removed and sorting is disabled.
