### ISSUE TITLE
Improve error message when probcli cannot be started

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#15]
Currently the message when ProB2 cannot start probcli is not very user-friendly.

Instead of saying, something like
 "Not enough memory to start probcli (exit code 137)" or
 "An error occured while starting probcli: exit code 137  (with path to probcli...)"
we get:
<pre>
   com.google.inject.ProvisionException: Unable to provision, see the following errors:
259    1) Error in custom provider, de.prob.exception.CliError: CLI exited with status 137 while matching output patterns
260      while locating de.prob.cli.ProBInstanceProvider
261      while locating de.prob.cli.ProBInstance
262        for the 1st parameter of de.prob.animator.AnimatorImpl.<init>(AnimatorImpl.java:38)
263      while locating de.prob.animator.AnimatorImpl
264      while locating de.prob.animator.IAnimator
265      at de.prob.statespace.StateSpace.<init>(StateSpace.java:99)
266      while locating de.prob.statespace.StateSpace
267    1 error
268        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
269        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1053)
270        at de.prob.scripting.StateSpaceProvider.getStateSpace(StateSpaceProvider.java:34)
271        at de.prob.model.representation.AbstractModel.load(AbstractModel.java:128)
272        at de.prob.scripting.ExtractedModel.load(ExtractedModel.java:28)
273        at de.prob.statespace.StateAnimationTest.setupSpec(StateAnimationTest.groovy:21)
274        Caused by:
275        de.prob.exception.CliError: CLI exited with status 137 while matching output patterns
276            at de.prob.cli.ProBInstanceProvider.startProlog(ProBInstanceProvider.java:96)
277            at de.prob.cli.ProBInstanceProvider.get(ProBInstanceProvider.java:50)
278            at de.prob.cli.ProBInstanceProvider.get(ProBInstanceProvider.java:28)
279            at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:85)
280            at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:77)
281            at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:59)
282            at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
283            at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
284            at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
285            at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
286            at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
287            at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
288            at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
289            at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
290            at de.prob.statespace.StateSpace.<init>(StateSpace.java:100)
291            at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
292            at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
293            at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
294            at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
295            at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
296            ... 4 more
297            Caused by:
298            de.prob.exception.CliError: Missing info from CLI PortPattern
299                at de.prob.cli.ProBInstanceProvider.analyseStdout(ProBInstanceProvider.java:164)
300                at de.prob.cli.ProBInstanceProvider.extractCliInformation(ProBInstanceProvider.java:131)
301                at de.prob.cli.ProBInstanceProvider.startProlog(ProBInstanceProvider.java:90)
302                ... 23 more
</pre>

**Comment by dgelessus** [comment]
hhu-stups/prob2_kernel@80ef18df199db23113b62ff2bd193203f3036734 makes the messages a bit more readable. I don't think we can improve much else about this message though. Showing just the exit code as a number isn't very nice, but it's all the information we get if the process exits. (If probcli printed any output before exiting, that should already be logged before the error.) The "Unable to provision" wrapper exception comes from Guice, so we can't change anything about that.
