### ISSUE TITLE
VisB: after opening new VisB JSON file no visualisation is visible

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#152]
After opening new VisB JSON file no visualisation is visible, one has to explicitly press the reload button in ProB2-UI to see the visualisation.

**Comment by favu100** [comment]
~~Seems to be an issue that only appears for XTL models~~ This also happens for models other than XTL. The problem is described below

**Comment by favu100** [comment]
It seems that the visualization is not updated when the new visualization file is equal to the previous visualization file

**Comment by favu100** [comment]
This issue should be fixed now
