### ISSUE TITLE
ModelCheckingOptions.FIND_OTHER_ERRORS is wrongly named

### ISSUE THREAD

**Issue by iTitus** [hhu-stups/prob-issues#160]
It's real meaning is `ignore_state_errors`.

Fixing possibilities:
 - Rename option in prolog, undo negation of option in Java & UI
 - Rename option in Java Kernel, undo negation in Java & UI
 - Refactor all options into a new class: also includes the limits and other options

**Comment by dgelessus** [comment]
Fixed in hhu-stups/prob2_kernel@e9d9e79e5c5b03c3b49e9039e77a110b54a74c4f.
