### ISSUE TITLE
dpllt_solver module calls non-existing preprocess_predicate/5 predicate

### ISSUE THREAD

**Issue by pmoura** [hhu-stups/prob-issues#166]
The `dpllt_solver` module calls a non-existing `preprocess_predicate/5` predicate around line 183 in the definition of the `get_amount_of_sat_variables/2` predicate. Found using the Logtalk linter:

```text
*     Unknown predicate called but not defined: preprocess_predicate/5
*       while compiling object dpllt_solver
*       in file /Users/pmoura/ProB_src/src/dpllt_solver/dpllt_solver.pl between lines 170-186
```

There is, however, a `preprocess_predicate/6` predicate exported by the `dpllt_preprocessing` module.

**Comment by dgelessus** [comment]
Fixed, thanks.

I thought we had caught all of these already - SWI also warns about calls to nonexistant predicates. I think this is one of the files that we currently have disabled on SWI.

**Comment by Joshua27** [comment]
Thank you. Fortunately, the affected predicate `get_amount_of_sat_variables/2` was only used for benchmarking and is *not* part of ProB's SMT solver.
