### ISSUE TITLE
Replacing calls to the legacy assert/1 predicate with the standard assertz/1 predicate

### ISSUE THREAD

**Issue by pmoura** [hhu-stups/prob-issues#170]
Calls to the legacy `assert/1` predicate can be replaced with calls to the standard `assertz/1` predicate. This is a fix that, thankfully (given the number of calls), can be done with a simple global search and replace.

**Comment by dgelessus** [comment]
It wasn't quite as simple as a global search/replace - we have a few places where `assert` is used as a regular identifier that has nothing to do with the `assert/1` predicate 🙂 Should be all done now though.
