### ISSUE TITLE
Unknown predicates called in `test_runner.pl`

### ISSUE THREAD

**Issue by pmoura** [hhu-stups/prob-issues#179]
```text
*     Unknown predicate called but not defined: format_warning_nl/1
*       while compiling object test_runner
*       in file /Users/pmoura/ProB_src/src/test_runner.pl between lines 858-859
*     
*     Unknown predicate called but not defined: probcli_binary/8
*       while compiling object test_runner
*       in file /Users/pmoura/ProB_src/src/test_runner.pl between lines 1453-1462
```

The first seems to be just a missing second argument (the empty list?).

**Comment by leuschel** [comment]
Thanks, fixed the first one.
The second one is defined in a local file ('probcli_bak/codespeed_versions.pl'), which specifies which probcli binary versions are available.

**Comment by pmoura** [comment]
I did noticed the comment in the second case but I could not find the `codespeed_versions.pl`.

**Comment by leuschel** [comment]
Indeed, it is not checked in. Probably it is currently only available on my laptop for performance regression analyses. I will try to add a default definition.
