### ISSUE TITLE
Avoid name clash with built-in `ignore/1` predicate in `proz/ztransformations.pl`

### ISSUE THREAD

**Issue by pmoura** [hhu-stups/prob-issues#191]
Both SWI-Prolog and Logtalk provide a built-in `ignore/1` meta-predicate (with the same semantics). Currently, the `proz/ztransformations.pl` source file defines a local `ignore/1` predicate. Renaming this local predicate (to `ignore_name/1` ?) would avoid the name clash.

**Comment by leuschel** [comment]
This is fixed.
