### ISSUE TITLE
Missing `dynamic/1` directive for predicate `complete_discharged_info/0` in `bmachine.pl`

### ISSUE THREAD

**Issue by pmoura** [hhu-stups/prob-issues#192]
Could you add the following directives to `bmachine.pl` (possibly around line 751):

```logtalk
:- volatile complete_discharged_info/0.
:- dynamic complete_discharged_info/0.
```

When Logtalk tries to compile the module, it throws an existence error for this predicate. This happens because while the standard `retractall/1` predicate is happy with unknown arguments, Logtalk is more strict and requires the argument to be for a declared dynamic predicate. Thanks.

**Comment by leuschel** [comment]
Fixed.
