### ISSUE TITLE
Operator clash in `btypechecker.pl`

### ISSUE THREAD

**Issue by pmoura** [hhu-stups/prob-issues#193]
The `btypechecker` module declares an infix `(::)/2` operator around line 73:

```logtalk
% operator for type inference rules
:- op(800,xfx,::).
```

Unfortunately, the `::` operator is key for Logtalk where it's used for message sending with a conflicting definition:

```logtalk
% message sending to an explicit object
:- op(600, xfy, ::).
% message sending to "self"
:- op(600,  fy, ::).
```

I have hardened some of the Logtalk developer tools for possible redefinitions  of the operator but that doesn't prevent all clashes. Also, as you know, operators declared inside modules are global in SICstus. The operator  seems to only be used for file terms in the `btypechecker.pl` file. It would be possible to use a different operator name? E.g. `<:>`? Please note that simply changing from `op(800,xfx,::)` to `op(600, xfy, ::)` in the file doesn't work as that would cause the Logtalk compiler to try to interpret `A :: B` facts or rule heads as for Logtalk multifile predicates.

**Comment by leuschel** [comment]
I have changed :: to <:> in btypechecker.pl.
