### ISSUE TITLE
Superfluous uses of the `append/3` predicate

### ISSUE THREAD

**Issue by pmoura** [hhu-stups/prob-issues#207]
Some superfluous uses of the `append/3` predicate:

In the `test_typechecker.pl` file around line 62, the goal `append(['T','E','S','T','_'],CName,CFullname)` can be rewritten as `CFullname = ['T','E','S','T','_'| CName]`.

In the `coverage/coverage_tools.pl` around line 315, the goal `append([url(URL)],RowAttrs2,RowAttrs3)` can be rewritten as `RowAttrs3 = [url(URL)| RowAttrs2]`.

In the `synthesis/deep_learning/b_machine_identifier_normalization.pl` around line 341, the goal `append([83], CIndex, CString)` can be rewritten as `CString = [83| CIndex]`.

Also related:

In the `symbolic_model_checker/kinduction.pl` around line 177, the goal `append([Conj1,Conj2],Conjuncts)` can be rewritten as `append(Conj1, Conj2, Conjuncts)`.

**Comment by pmoura** [comment]
Also in `bsyntaxtree.pl`, around line 2379, there three occurrences of the goal `append([[TID],[A],[Expr]],Exprs)`, which can be simplified to `Exprs = [TID, A, Expr]`.

**Comment by leuschel** [comment]
The three uses of append/2 in bsyntaxtree.pl have been rewritten.
