### ISSUE TITLE
Change machine locations in project

### ISSUE THREAD

**Issue by favu100** [hhu-stups/prob-issues#216]
It seems that it is not possible to change the machine locations in the project. This should be fixed

**Comment by iTitus** [comment]
> Currently, it is not possible to change the path of the machine in the project file via ProB2-UI (only possible by changing the machine path in the prob2project file manually).
This is feature is helpful when the machine file changes while the modeler might want to use the validation tasks and VOs.

**Comment by dgelessus** [comment]
This should probably be added in the "Edit Machine..." dialog (accessible via the context menu), where one can already change the machine name and description.
