### ISSUE TITLE
Removing requirement from VO manager is not clean

### ISSUE THREAD

**Issue by SeeBasTStick** [hhu-stups/prob-issues#220]
When currently adding VOs, one just inserts them into the empty field without additional confirmation. Instead it looks like one has to press the 'Apply' button which is confusing.

**Comment by dgelessus** [comment]
Yes, right now it's easy to accidentally lose changes in the requirement editing view if you click elsewhere. We should probably add a warning dialog when there are unsaved changes. Or we could make the VO table apply its changes right away, as soon as you press Enter in the validation expression text box.

**Comment by dgelessus** [comment]
Fixed in hhu-stups/prob2_ui@3e27c4c344a0744ed0276274cc198554c81d0cea - changes to VOs are now saved immediately without having to click Apply.
