### ISSUE TITLE
Make a list of VTs availible

### ISSUE THREAD

**Issue by SeeBasTStick** [hhu-stups/prob-issues#221]
It is hard to remember the correct syntax while typing. Some support in form of a cheat sheet would be helpful.

**Comment by dgelessus** [comment]
The dropdown menu of the expression text field shows all the available validation tasks:

<img width="703" alt="grafik" src="https://user-images.githubusercontent.com/6641959/194096530-6fb5824b-36d2-4f02-a16e-6a9feef1a61d.png">

But this isn't a very good solution for writing complex validation expressions. Maybe we should implement proper code completion while typing, or a second table showing all available VTs in the selected machine?

**Comment by dgelessus** [comment]
> a second table showing all available VTs in the selected machine

This was implemented in hhu-stups/prob2_ui@bde0915c975096ec390b1744a442668b0fd672c6.
