### ISSUE TITLE
Multi-Line Input in ProB2-UI Console not working properly

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#231]
When typing multi-line formulas in the ProB2-UI console only the last
line seems to be processed.
In the probcli REPL this works like this:
```
>>> 1 + \
... 2
Expression Value = 
3
```
In ProB2-UI it returns 2.

**Comment by iTitus** [comment]
I fixed it, but there might be weirdness when using the Arrow-Up-Key after entering a multi-line input.
