### ISSUE TITLE
Requirements are only loaded when machine is loaded.

### ISSUE THREAD

**Issue by SeeBasTStick** [hhu-stups/prob-issues#234]
In the VO manager requirements are only loaded if the corresponding machine is loaded.

In the pictures one can see, that in the machine view, requirements concerning the not loaded machine are not visible.

![image](https://user-images.githubusercontent.com/49205030/196720619-918fea4a-999d-4014-ad3f-38cededb40ea.png)

![image](https://user-images.githubusercontent.com/49205030/196720744-7aabbeba-59c5-461b-9f61-0c9f44f23e33.png)

**Comment by dgelessus** [comment]
IIRC, we implemented this on purpose - the VO manager only shows machines that are part of the refinement chain of the currently loaded machine. But I personally also find this confusing. Maybe the machines outside the refinement chain should be shown in the VO manager, but grayed out?

You can also switch to "Group by: Requirement" to show all requirements, regardless of what machine they belong to (but the individual VOs belonging to unrelated machines are still hidden).

**Comment by SeeBasTStick** [comment]
Yes, I observed the same and agree. It should at least be "there".

**Comment by dgelessus** [comment]
Fixed in hhu-stups/prob2_ui@225a550a3228295bf76e266d16472a32bb380880.
