### ISSUE TITLE
Order of machines is saved in project file and cannot be changed easily

### ISSUE THREAD

**Issue by dgelessus** [hhu-stups/prob-issues#235]
Machines are stored in the project in the order in which they were originally added, but this isn't always the most useful order. For example, when you have multiple machines in a refinement chain, you usually want the abstract machine before the refined one - but if you add the refined machine to the project first, the order will be wrong.

We should either allow reordering existing machines in a project (by drag-and-drop), or we should remove ordering entirely and always sort machines alphabetically by their name.

**Comment by iTitus** [comment]
Implemented with buttons.

**Comment by iTitus** [comment]
[Screencast from 10-24-2022 02:09:55 PM.webm](https://user-images.githubusercontent.com/5154317/197522432-0f4c4eac-c2c3-436f-a4e4-c46c459a0c31.webm)
