### ISSUE TITLE
Order of modelchecking options in prob2project file is not stable

### ISSUE THREAD

**Issue by dgelessus** [hhu-stups/prob-issues#244]
When saving a ProB 2 project containing a modelchecking item, the options are saved in an unpredictable order. This can lead to unnecessary changes when re-saving an existing project. For example:

```diff
@@ -42,8 +42,8 @@
         {
           "searchStrategy": "MIXED_BF_DF",
           "options": [
-            "FIND_DEADLOCKS",
-            "FIND_INVARIANT_VIOLATIONS"
+            "FIND_INVARIANT_VIOLATIONS",
+            "FIND_DEADLOCKS"
           ],
           "shouldExecute": true
         }
```

The options should always be sorted in some order that remains stable across multiple runs of ProB 2 UI (probably using the default `Enum.compareTo` ordering). I already tried to fix this by using a `TreeSet` (which sorts its contents) to serialize `ModelCheckingOptions.Options` in `ProB2JacksonModule`, but apparently that didn't help.

**Comment by iTitus** [comment]
Previous attempt used the wrong types, fixed as of https://github.com/hhu-stups/prob2_ui/commit/c8e616ae99f17f00c96a03cb15c5c1a185809456
