### ISSUE TITLE
prob jupyter kernel issues

### ISSUE THREAD

**Issue by DavidPratten** [hhu-stups/prob-issues#249]
Hi Team,

Not sure if this is the right place, but I can't seem to send feedback via https://gitlab.cs.uni-duesseldorf.de/general/stups/prob2-jupyter-kernel

1. I'm trying to install the ProB Jupyter Kernel and the latest jar prob2-jupyter-kernal-1.3.0-all.jar doesn't appear to contain the __main__.py required for installation?
2. After launching the Jupyter Kernel using binder, the kernel seems to be unavailable. 
![image](https://user-images.githubusercontent.com/1667631/205436794-672045f8-27a4-4a91-a905-bef2671757a4.png)

If you could pass this on to the right people, that would be great.

David

**Comment by dgelessus** [comment]
Thanks for the report. The installation instructions should be correct again now.

The instructions you saw before are for the next version of the kernel, which hasn't been released yet. Sorry for the confusion!
