### ISSUE TITLE
Traces checking for predicates and/or enabledness cannot be replayed

### ISSUE THREAD

**Issue by cobizobi** [hhu-stups/prob-issues#250]
In the current snapshot-version of ProB2-UI, I get the following error message when I try to replay a trace that checks for a predicate and/or enabledness of an operation:

`Error: Could not translate JSON transitionList:  json([=(description,string([]),2-2),=(transitionList,[json(...),json(...)|...],3-1644),=(variableNames,[...|...],... - ...),=(...)|...])`

Removing the checks results in a successful replay.

**Comment by dgelessus** [comment]
Fixed now on the Prolog side. The fix should be included in the next snapshot build of ProB 2 UI.
