### ISSUE TITLE
State Space Projection and Operation Coverage only for parts of state space that are visited

### ISSUE THREAD

**Issue by favu100** [hhu-stups/prob-issues#252]
In the future, it would be useful to create projections, and to evaluate coverage only on parts of the state space that was visited.
Currently, the ProB animator (or at least ProB2-UI?) always compute the next transitions. Therefore, they are also considered as explored.

**Comment by leuschel** [comment]
I have added a new preference DOT_PROJECTION_ONLY_EXPLORED_NODES for this in commit:
3b77affa add preference to only project on explored states
