### ISSUE TITLE
ProB2-UI Exceptions when trace file does not exist

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#257]
There are a few problems when a trace file no longer exists.

First, upon attempting replay one gets a dialog which we could make clearer by stating the the JSON file does not exist (rather than that it could not be loaded):

<img width="349" alt="Screenshot 2022-12-16 at 17 13 27" src="https://user-images.githubusercontent.com/1742246/208141368-8b406c53-5901-400a-9d8c-703a74dd6999.png">

Second, when one uses Show Replay Status or various other inspection commands one gets an internal exception:

```
java.lang.IllegalArgumentException: javafx.fxml.LoadException: 
/Users/leuschel/git_root/JAVAPROB/ui-prob2/build/resources/main/de/prob2/ui/sharedviews/description_view.fxml
...
```

**Comment by iTitus** [comment]
fixed, error message is also clearer
