### ISSUE TITLE
Setting default VisB JSON file only takes effect when saving project

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#259]
When one sets the default VisB visualisation, changes machine and changes back the VisB visualisation is
not shown, one has to open and choose the VisB file again to display it.
Alternatively, saving the project and reloading the machine works.
Ideally, saving should not be required for the VisB file to be automatically shown.

I would also suggest we set the default VisB file automatically, when opening the first VisB file for a model.

**Comment by iTitus** [comment]
Projects are marked as changed and thus trigger a user confirmation when trying to load a different one.
When reloading a machine the default visualization is kept.
