### ISSUE TITLE
Provide LTL Limit parameter in ProB2-UI for LTL formulas

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#261]
ProB has an LTL limit parameter for checking LTL checks: it specifies the maximum number of states explored.
It may be interesting to set this as an optional parameter for LTL checks.
ProB Tcl/Tk also provides the option to start in the current state or in initial states; this could also be useful.

Finally, it seems that at least sometimes the LTL check is marked with a green checkmark as verified when the LTL limit (default value 10000) is reached.

**Comment by leuschel** [comment]
Actually, it seems that ProB2-UI now calls the command with a limit of -1, meaning that all nodes will be explored.

**Comment by iTitus** [comment]
Implemented, although there are issues with the backend.

![image](https://github.com/hhu-stups/prob-issues/assets/5154317/0e1aa6cd-756c-4e63-a9b6-312eb537f715)
