### ISSUE TITLE
Toolbar button icons are sometimes replaced with "..."

### ISSUE THREAD

**Issue by dgelessus** [hhu-stups/prob-issues#266]
In some views with toolbars, e. g. the Operations view, the toolbar button icons are replaced with "..." if the view is very narrow:

![Operations view screenshot](https://user-images.githubusercontent.com/6641959/212305494-c8da54c7-22d2-4184-9228-7e594fb612a1.png)

This should never happen, because the buttons become unrecognizable if replaced with "...", and the replacement doesn't save any horizontal space.

The underlying cause is probably that we use an "icon font" and the ControlsFX `Glyph` class, which is based on a text `Label` instead of an image view, so JavaFX tries to truncate it like normal text. If possible, we should disable truncation for all of our `Glyph`s.

**Comment by SherinSchneider** [comment]
buttons should not be replaced with "..." anymore
