### ISSUE TITLE
Some table selection colors have bad contrast with text

### ISSUE THREAD

**Issue by dgelessus** [hhu-stups/prob-issues#267]
For example in the project machine list:

![Bad contrast screenshot](https://user-images.githubusercontent.com/6641959/212306388-78d15be5-1218-46f8-b0bb-8e85deee4567.png)

Especially when hovering over the selected item:

![Bad constrast screenshot with hover](https://user-images.githubusercontent.com/6641959/212306449-1f87fd8e-4de9-4f29-b8b2-9611ce14b3c6.png)

**Comment by Inab1993** [comment]
By changing -fx-background to -fx-background-color in the rule .list-cell, the fontcolor of the odd rows becomes white. But when switching to e.g. "projects" and back to "machines", the fontcolor is black again and you have to re-select the cell.
