### ISSUE TITLE
ProB message alert is titled "Warning" even if there are no warnings

### ISSUE THREAD

**Issue by dgelessus** [hhu-stups/prob-issues#273]
For example, this alert contains only entries of type "Message" and none of type "Warning", but the overall title still says "Warning":

!["Warning" alert screenshot](https://user-images.githubusercontent.com/6641959/212861241-457c3c9e-5b9e-43be-a07e-913c62e3911e.png)

It should only say "Warning" if there is at least one warning in the list, otherwise "Message".

**Comment by yutak001** [comment]
Type and content of the alert will be set according to the highest level of error item now.
