### ISSUE TITLE
ProB2-UI Animation Replay View

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#278]
It would be nice to have a bit more information about the traces in the Replay tab of the Animation view.
For example, it would be nice to see the number of steps of the trace.

**Comment by iTitus** [comment]
implemented in https://github.com/hhu-stups/prob2_ui/commit/b7470b19ee52d5f14029eefa7e9fc0ede592c780
![image](https://github.com/hhu-stups/prob-issues/assets/5154317/2bc2484e-64fb-458d-a0fb-cf9b62d18a0f)
