### ISSUE TITLE
EvalB generates wrong variable declaration for CHOOSE

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#293]
When typing ```CHOOSE x \in 0..100: x^3 - 20*x^2 + 7*x = 14388``` into EvalB
we get an error during evaluation due to multiply defined variable x.
The generated TLA module has an unnecessary Variable declaration:

```
----MODULE TestConstraint ----
EXTENDS Naturals, Integers, Sequences, FiniteSets 
VARIABLES x
Expression == CHOOSE x \in 0..100: x^3 - 20*x^2 + 7*x = 14388
====================
```

**Comment by leuschel** [comment]
The TLA Module seems to be created in
tla2bAST within src/main/java/de/tla2bAst/ExpressionTranslator.java:
```
		StringBuilder sb = new StringBuilder();
		sb.append("----MODULE " + moduleName + " ----\n");
		sb.append("EXTENDS Naturals, Integers, Sequences, FiniteSets \n");
		if (variables.size() > 0) {
			sb.append("VARIABLES ");
```

**Comment by leuschel** [comment]
Issue is hopefully solved in commit:
hhu-stups/tla2bAST@3d4225dd fix issue 293 involving evaluation of CHOOSE expressions

**Comment by iTitus** [comment]
Is this still a problem? If yes re-open please.
