### ISSUE TITLE
Add syntax highlighting in ProB2-UI BEditor for special DEFINITIONS

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#294]
It would be nice to highlight some special DEFINITIONS that ProB recognises:
- VISB_JSON_FILE
- VISB_SVG_BOX
- VISB_SVG_OBJECTS..
- VISB_SVG_UPDATES..
- VISB_SVG_HOVERS...
- ASSERT_LTL..
- ASSERT_CTL...
- SET_PREF_
- GOAL
- SCOPE
- scope_....
- ... (see Tk syntax highlighting rules)

**Comment by leuschel** [comment]
The Tcl code contains e.g.:
`{&|(?=\m)(not|or|btrue|bfalse|TRUE|FALSE|bool|GOAL|SCOPE|ANIMATION_IMG\w*|ANIMATION_STR\w*|ANIMATION_FUNCTION_DEFAULT|ANIMATION_FUNCTION[0-9]*|ANIMATION_RIGHT_CLICK|ANIMATION_CLICK|HEURISTIC_FUNCTION|VISB_JSON_FILE|VISB_SVG_BOX|VISB_SVG_OBJECTS\w*|VISB_SVG_HOVERS\w*|VISB_SVG_UPDATES\w*|CUSTOM_GRAPH_EDGES|CUSTOM_GRAPH_NODES|ASSERT_(LTL|CTL)\w*)(?=\M)|<?=>|!|#}`

**Comment by dgelessus** [comment]
Implemented in hhu-stups/prob2_ui@ba1575aa8b9fd3d4e5d43a5e4a63febca0f62d2b.

The special identifiers are recognized using the method `Utils.isProBSpecialDefinitionName` from the B parser library. If any special identifiers are missing, please add them there.
