### ISSUE TITLE
Need to close and re-open VisB window in ProB2-UI to load default visualisation

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#301]
I have had the VisB window open for a first model, then I switched
to another B model which had a VISB_JSON_FILE definition.
However, the VisB window was empty. I had to close the window
and re-open it for the VisB default visualisation to be shown.

**Comment by iTitus** [comment]
Was fixed in https://github.com/hhu-stups/prob2_ui/commit/ef201dd6b476f0cade2240eb5f0a1e1689e73662

![image](https://github.com/hhu-stups/prob-issues/assets/5154317/15ee01ce-28b5-4c27-8e3a-5728beb1f617)
