### ISSUE TITLE
Improve indentation in Value dialog of ProB2-UI State View

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#303]
It would be nice if Prettify also indents the record fields of values.
Possibly it would also be nice to have a checkbox option (next to Prettify) to see the full value and not truncate it.
Also, maybe we could have an option to directly show sets/relations/records as tables (possibly by opening the corresponding sub-view of the Table Visualisation window like "Visualize Expression Value as Table" right click.

**Comment by leuschel** [comment]
![Screenshot 2023-03-03 at 10 04 43](https://user-images.githubusercontent.com/1742246/222678349-c71f4b56-1e7b-4ec8-8517-550798c110ca.png)

**Comment by Inab1993** [comment]
- added a checkbox to show full values (at least up to the current limit of 600chars)
- added a contextmenu to the current value-tab to visualize values as graphs or tables

**Comment by iTitus** [comment]
Please re-open if this is still a problem
