### ISSUE TITLE
CSP : channel of type Set, error in synchronisation

### ISSUE THREAD

**Issue by gevegab** [hhu-stups/prob-issues#304]
Hello

I am trying to define a CSP process that uses a channel of type Set to synchronize a parallel composition. When I try to animate the process, I get an error message dialog box. The problem arises even if I only animate the CSP without synchronizing with a B machine. After the error I can continue the animation, and it seems to work, so I am not sure if this is a real error or simply a warning.

Here is a minimal example showing the problem:

```
datatype DATA = DATA1 | DATA2
nametype  INPUT= Set(DATA)

channel	produce : INPUT
channel	consume :INPUT
channel	message : INPUT

MAIN = PRODUCER [| {|message|} |] CONSUMER

PRODUCER =  produce?i -> message!i -> STOP
CONSUMER =  message?i -> consume!i -> STOP
```

This is the error message I get

```
Warning: Illegal data value:  setValue(['DATA1','DATA2']):outer(unify_arg(in(_413113),setValue([...|...]))):  Context =  ERROR CONTEXT: CHANNEL:ALL, State ID:1,
 ### Line: 11, Column: 25 until 32
```
If I change the channel type to a simple datatype (i.e. nametype  INPUT= DATA) everything works without error messages

Thank you

**Comment by leuschel** [comment]
The issue should be solved in commit 727e93542e25fd1c322c2e435948ed489d4bbe46.
The fix will be available in the next nightly release.

**Comment by gevegab** [comment]
Hello,

Thank you for your reactivity. I would like to test, but I cannot find the nightly release at https://stups.hhu-hosting.de/downloads/prob/tcltk/nightly/ , is there another site to download it?

Thank you very much again

**Comment by leuschel** [comment]
We had some trouble with our build bots; but there should be a working new nightly version on the site above.

**Comment by gevegab** [comment]
Hello

I have just tested with nightly version of 2023-03-17 , and everything goes well.

Thank you
