### ISSUE TITLE
Save history causes freeze of UI after find_valid_state command

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#31]
After running a find valid state command (Symbolic pane of the Animation view), a click on the save icon in the history view causes this error message.
Thereafter the UI is not responsive anymore. A reload is, however, possible and after that the UI is working again.

![Screenshot 2021-02-23 at 15 06 18](https://user-images.githubusercontent.com/1742246/108856959-e2a20c80-75ea-11eb-94a6-d7869ddda2cd.png)

**Comment by favu100** [comment]
This issue should be fixed now
