### ISSUE TITLE
Parser for Rules machines does not accept pragmas for constants

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#316]
It seems that at least for constants the Rules machine parser does not accept pragmas.

**Comment by iTitus** [comment]
Do you have an example rules machine?

**Comment by cobizobi** [comment]
Some examples are in `Rules_Machines` or `Rules` in the public examples.

**Comment by iTitus** [comment]
Sorry, I meant a rules machine with a correct pragma comment that does not work.

**Comment by cobizobi** [comment]
As an example try to add a description pragma to a constant in `CONSTANTS` section. This is currently not recognised in rules machines and gives `Error: Identifier expected`. The pragma must probably also be transferred to the internal representation of the machine.

**Comment by iTitus** [comment]
I added support for description pragmas
