### ISSUE TITLE
Reloading machine in ProB2-UI discards unsaved changes

### ISSUE THREAD

**Issue by cobizobi** [hhu-stups/prob-issues#318]
Unsaved changes to a machine that were previously made in the ProB2-UI Editor are discarded without any warning when the machine is reloaded. The old version of the machine will be loaded. Before reloading, there should be a prompt asking whether the changes should be saved.

**Comment by iTitus** [comment]
Fixed in https://github.com/hhu-stups/prob2_ui/commit/6eb74f348f606e0dcf7486fc7b8c8ac9db7139b5
