### ISSUE TITLE
ProB black Window problem

### ISSUE THREAD

**Issue by jingsun062** [hhu-stups/prob-issues#322]
When I launch the ProB tool on my Mac laptop after the installation, the black window problem occurred. I double checked that the version of tcl/tk is correct (i.e., 8.6.13_4) and it was newly installed. I am not sure what the settings need to be changed to get rid of the black window issue? Many thanks.

Cheers, Jing

**Comment by leuschel** [comment]
Which version of ProB do you use? Have you installed Tcl/Tk with MacPorts or with Homebrew?
Have you tried launching ProB with the StartProB.sh script; it should auto-detect MacPorts and Homebrew installations and set SP_TCL_DSO so that the underlying Prolog can find the right Tcl/Tk.
I would recommend trying the current nightly build.

**Comment by leuschel** [comment]
I have updated the wiki page https://prob.hhu.de/w/index.php?title=Download#Tcl%2FTk_on_macOS slightly to mention the shell script to start ProB.

**Comment by jingsun062** [comment]
Thank you for the prompt reply, much appreciated. I tried launching ProB with the StartProB.sh script, which worked.

Now the ProB can view can run models, however, the visualization function not working (even that I installed the graphviz software. Can you advise how to fix this issue? Many thanks.

PS: I am using the latest ProB 1.12.1-final version.

**Comment by leuschel** [comment]
What exactly is the problem with visualization? Are you trying to use state space visualisation?
Have you looked at https://prob.hhu.de/w/index.php?title=Download#Graphviz_Requirements?
You should probably select Preferences -> Graphical Viewer -> PDF, as currently all GraphViz viewer applications on macOS seem to crash on current macOS systems.
You can try setting the DOT (path_to_dot) preference if ProB does not find the dot binary.

**Comment by jingsun062** [comment]
Thank you for the quick answer. Yes, setting the Preferences -> Graphical Viewer -> PDF worked.
