### ISSUE TITLE
Editor discards changes made during loading

### ISSUE THREAD

**Issue by iTitus** [hhu-stups/prob-issues#327]
Solutions:
- ~~disable editing during loading~~
- don't re-load text at end of loading
- ~~add dialog/user interface for overwriting current text (always)~~

**Comment by dgelessus** [comment]
Small note: if possible, I think we should avoid disabling the editor, because this leads to bad user experience - if the user notices an error while the machine is loading, they would be unable to fix the error until the machine is done loading.

**Comment by iTitus** [comment]
fixed in https://github.com/hhu-stups/prob2_ui/commit/e103ab3f98447ebbd5fd470cb971653976c0dec9
