### ISSUE TITLE
Provide additional predicate for the explicit model checking command

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#33]
The explicit model checking command can search for states satisfying a GOAL predicate. In Event-B this goal predicate cannot be provided by the user, hence it would be nice if the UI were to provide a way to enter an additional target predicate in the regular explicit model checking command.

**Comment by dgelessus** [comment]
This is already implemented in the ProB 2 API - the `ConsistencyChecker` constructor takes an optional goal predicate as the third parameter. I think we just need to add a corresponding text field in the UI.

**Comment by favu100** [comment]
Currently, model checking with goal results in an error (red X) when a goal is found. This might be a little bit confusing

**Comment by favu100** [comment]
This feature is now implemented
