### ISSUE TITLE
Generated traces by SimB are not saved at the selected location

### ISSUE THREAD

**Issue by cobizobi** [hhu-stups/prob-issues#331]
On Windows, generated traces by SimB are saved in the default folder of the user profile instead of the selected location and the selected file name is also not used (at least for me).

**Comment by favu100** [comment]
I cannot reproduce this issue. However, another bug has been fixed which is related to this bug. Is this still an issue?

**Comment by cobizobi** [comment]
This seems to have fixed my problem too. It works now.
