### ISSUE TITLE
Warning when loading a prob2trace in ProB2-UI

### ISSUE THREAD

**Issue by cobizobi** [hhu-stups/prob-issues#334]
Sometimes, when replaying a saved `.prob2trace` in ProB2-UI, I get the following warning:
```
[INFO] ! A warning occurred (source: replay_json_trace_file) !
[INFO] ! JSON trace file model name Test.mch does not match current model name: Test
```
Unfortunately, I have not yet been able to reproduce it.

**Comment by iTitus** [comment]
Closing because not reproduceable
