### ISSUE TITLE
Warnings when doing Trace Replay

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#344]
The warnings during trace replay in ProB2-UI should not be shown as a separate dialog, but in the main trace replay dialog.
Also, there seems to be no difference between the accept and discard buttons?

Finally, one cannot copy the message in the second warning dialog.

**Comment by leuschel** [comment]
<img width="614" alt="Screenshot 2024-03-28 at 18 50 45" src="https://github.com/hhu-stups/prob-issues/assets/1742246/0513693b-92c1-459f-a419-7eb111ab098f">

**Comment by leuschel** [comment]
First dialog: 
<img width="738" alt="Screenshot 2024-03-28 at 18 53 00" src="https://github.com/hhu-stups/prob-issues/assets/1742246/b03aac2b-8f34-42ec-ab40-709a4d63b560">

**Comment by leuschel** [comment]
The Warning about the model should probably also only be shown when trace replay fails.

**Comment by yutak001** [comment]
I added a context menu to the message cell so error messages can be copied to the system clipboard.

As for the discard/accept buttons: When I am using these buttons discard leaves the history as it is whereas accept replaces the currently used trace in the history view by the corrected version of the trace replay. The replacing process seems to take a while, at least in some cases.

**Comment by leuschel** [comment]
Maybe we should rename "Accept" to "Partial Replay" and Discard to "Cancel"?

**Comment by yutak001** [comment]
I'm not sure if that is clear enough. I added a question label to explain the function of these buttons
![Screenshot_20240404_164818](https://github.com/hhu-stups/prob-issues/assets/19926137/716f4934-9f5f-49a9-9cef-3e3ff16cbb40)
How about that?

**Comment by leuschel** [comment]
That is good. Just it ist not entirely clear what discard means: delete the trace file and remove it from the project, remove the trace from the project, or not replay the partially replayed trace but keep it.
I always thought it was the latter (as a user can always remove a trace by other means).

**Comment by iTitus** [comment]
It will not change the project, just the current history (trace).
Discard leaves everything as it was before.

**Comment by leuschel** [comment]
Good. Then I would use cancel rather than discard for the button (cancel implies things stay the same for the user; discard implies we throw something away) and say something like "Do you want to perform the partial/imperfect trace replay?"

**Comment by yutak001** [comment]
I renamed the discard button and added the status of the trace replay to the question
![Screenshot_20240405_111119](https://github.com/hhu-stups/prob-issues/assets/19926137/2650b7a2-fc39-4a65-971c-79e899545907)
