### ISSUE TITLE
Improve message in ProB2-UI when dot not installed

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#346]
Currently the error message is not very instructive for the average user:

![dot_error_1](https://github.com/hhu-stups/prob-issues/assets/1742246/5fdf7441-43ec-4c27-8ee8-33e12eb04855)
![dot_error_2](https://github.com/hhu-stups/prob-issues/assets/1742246/188ad9fd-44a4-44ba-9987-75a995f80935)

**Comment by iTitus** [comment]
regression of #114 ?

**Comment by iTitus** [comment]
That fix only checked whether the DOT property was set.
I improved the error further:
![image](https://github.com/hhu-stups/prob-issues/assets/5154317/b0877d5c-aff7-4dac-b008-5a0fbd4c6341)
