### ISSUE TITLE
ProB2-UI Show Full Value does not show full value

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#347]
The description stops with ...
![Screenshot 2024-04-18 at 16 36 43](https://github.com/hhu-stups/prob-issues/assets/1742246/8f8940d3-53cb-4f71-b8dc-03456d7b7a2b)

**Comment by iTitus** [comment]
same issue as #93
Caused by the the Kernel or Prolog I think:
> _but is still limited to 600 chars currently_

**Comment by iTitus** [comment]
Fixed in dev, need a Prolog & Kernel release to use it in the UI
