### ISSUE TITLE
ProB2UI CTL model check does not work with XTL files

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#352]
There is a result_is_not_ground exception.
It seems like the Java side is parsing the CTL formula assuming that it is for a B model.

[DEBUG] Sending: prob2_do_ctl_modelcheck(ag(not(ap(enabled(bop(oppattern(pos(-1,-1,1,8,1,13),start,[])))))),[max_new_states(-1),mode(init)],R,CE),true.
[INFO] % No B machine available for 
[INFO] % b_get_machine_operation(start,_377941,_377943,_377931,_377933,_377935)
[INFO] exception(make_call/3, result_is_not_ground).
[ERROR] Unhandled exception during checking

**Comment by leuschel** [comment]
Maybe commit edd4612099575d0e11946be59e8d0cf72b4dfc55 in prob_prolog is already enough to fix this.

**Comment by iTitus** [comment]
It seems to work now
