### ISSUE TITLE
Changes are lost when switching between machines in ProB2-UI Editor

### ISSUE THREAD

**Issue by cobizobi** [hhu-stups/prob-issues#358]
I have made some changes to a machine in the ProB2-UI editor and switched to one of its included machines using the dropdown menu in the editor view (without loading a new machine). When I switch back to the edited machine, all unsaved changes are lost.

**Comment by iTitus** [comment]
https://github.com/hhu-stups/prob2_ui/commit/b1977eb17b4f29f9313b79aef6bb24f698bf73d2
