### ISSUE TITLE
Adding new machine with wrong or no extension to project leads to uncatched error

### ISSUE THREAD

**Issue by yutak001** [hhu-stups/prob-issues#37]
If a new machine is added to a project with wrong or no extension ProB2UI throws an uncatched error saying it does not know the machine type for this extension. 
`java.lang.IllegalArgumentException: Could not determine machine type for extension`
Not surprising but for the sake of completeness: Same result (but shorter trace) when trying to execute this machine (it was successfully added to the machine list).

**Comment by favu100** [comment]
Can you show a screenshot showing how you are adding a new machine (with no/wrong extension) to the project? I thought that one can only add machines matching the given extensions. This is at least the way how it behaves on Mac

**Comment by yutak001** [comment]
Plus sign -> Create New Machine:
![Screenshot_20210308_111255](https://user-images.githubusercontent.com/19926137/110307637-6f8f9180-7fff-11eb-9016-8b614867aae1.png)

Creating machine with name "Bla" by pressing enter and not choosing any extension:
![Screenshot_20210308_111555](https://user-images.githubusercontent.com/19926137/110307870-b8474a80-7fff-11eb-9c71-10388ea4b07c.png)

Resulting error messages:
![Screenshot_20210308_111802](https://user-images.githubusercontent.com/19926137/110308122-03f9f400-8000-11eb-8fa9-52760488a953.png)

Faulty machine has been added to the machines tab:
![Screenshot_20210308_112059](https://user-images.githubusercontent.com/19926137/110308453-6a7f1200-8000-11eb-86c5-d3f007bf1ef5.png)

**Comment by yutak001** [comment]
I added a warning followed by another try with the save dialog. For all OS not having this bug it should not matter. Reopen otherwise.
