### ISSUE TITLE
Parser check of definition parameters provides misleading message

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#371]
When you use a definition which takes say 5 parameters with 6 you get the error message
! Number of parameters (0) doesn't match declaration of definition TEXT_FIELD (5)

I guess since the nr of parameters do not match, the parser translates this to a definition call without parameters.
The check in DefinitionUsageCheck.java is possibly run too late:
```
private void check(final Node node, final int paramCount, final String literal) {
	final int expected = definitions.getParameterCount(literal);

	if (paramCount != expected) {
		exceptions.add(new CheckException("Number of parameters (" + paramCount + ") doesn't match declaration of definition " + literal + " (" + expected + ")", node));
	}
}
```

**Comment by iTitus** [comment]
Fixed in https://github.com/hhu-stups/probparsers/commit/98e99fea7f594846d168e4a483d49711d4c823b0
