### ISSUE TITLE
Enable pasting multi-line formulas into ProB2-UI Console

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#372]
Pasting multi-line formulas into the B console leads to errors.
It would be nice to add the \ at the end of all but the last line, for example, to enable pasting and
evaluating multi-line formulas in the console

**Comment by iTitus** [comment]
when pasting multi-line strings every line but the last will have a backslash now

**Comment by cobizobi** [comment]
However, these multi-line commands can only be restored line by line from the history. Maybe we can improve this.

**Comment by iTitus** [comment]
Implemented as well 👍
