### ISSUE TITLE
No feedback about VisB JSON file being used

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#374]
At the moment there seems to be no way for the user to find out
which VisB JSON file is being used (apart from inspecting the project file).
It would be nice to provide feedback and to maybe also be able to open the file in an external editor.
If DEFINITIONS are used this should also be made clear to the user.

**Comment by iTitus** [comment]
#340

**Comment by iTitus** [comment]
implemented in https://github.com/hhu-stups/prob2_ui/commit/d9f263025f954403e3a010be0f892ef6d0af4eb4
