### ISSUE TITLE
Save selected VisB JSON file automatically to project

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#375]
I think a chosen VisB JSON file should be put straightaway
as default visualisation in the project data, at least when no other
visualisation was selected before.

It happens quite often that one selects a VisB Json file and saves the
project expecting the VisB file to be saved for next time.
However, this is currently not the case, one first has to remember
to set the visualisation as the default one before saving.

(Maybe it would make sense to save a list of VisB configurations; even though it is probably not very common to have more than one visualisation.)

**Comment by iTitus** [comment]
#340

**Comment by iTitus** [comment]
implemented in https://github.com/hhu-stups/prob2_ui/commit/d9f263025f954403e3a010be0f892ef6d0af4eb4
