### ISSUE TITLE
Improve parse error message in Graph Visualisation window

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#40]
The parse errors contain the internal exception name. This is probably misleading to users.
Also, ideally we should highlight the error location in the formula view.
![Screenshot 2021-02-27 at 12 22 24](https://user-images.githubusercontent.com/1742246/109385777-a88c7f80-78f6-11eb-98b5-521603229e51.png)

**Comment by favu100** [comment]
The error message has been improved. Still, it does not provide any error location yet

**Comment by iTitus** [comment]
Related to #114

**Comment by iTitus** [comment]
also related to #164

**Comment by iTitus** [comment]
![image](https://github.com/hhu-stups/prob-issues/assets/5154317/8d96c953-885f-402c-baf2-fb0f4c29c462)
was fixed a while ago
