### ISSUE TITLE
Improve rendering of formula input field in Graph and Table Visualisation Views

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#41]
The text field is still not very clearly marked as an area where a user can type in a formula.

![Screenshot 2021-02-27 at 12 22 24](https://user-images.githubusercontent.com/1742246/109385820-da054b00-78f6-11eb-8c97-f22f09be2d66.png)

**Comment by favu100** [comment]
The style of the TextField now contains a border with ProB2-UI's standard color
