### ISSUE TITLE
State View for XTL is empty

### ISSUE THREAD

**Issue by favu100** [hhu-stups/prob-issues#46]
The State View for XTL is always empty. This is an issue since we have switched to BVisual2 (or at least since the last major update in BVisual2?).

**Comment by favu100** [comment]
The raw state is now shown in the State View for XTL specifications. The next step would be a dynamic tree view

**Comment by leuschel** [comment]
I guess you mean to say the raw state is *now* shown ;-)

**Comment by favu100** [comment]
Yes, I've corrected it in the comment

**Comment by iTitus** [comment]
Was recently improved by showing (a limited number of) the prop solutions
