### ISSUE TITLE
Detached views are sometimes reattached after restarting UI

### ISSUE THREAD

**Issue by dgelessus** [hhu-stups/prob-issues#5]
Recently, the state of detacted views isn't always persisted across restarts. It works most of the time, but in maybe 1 out of 5 restarts, all detached views are reattached. Other windows (like the state error details) are persisted reliably and don't get closed, even when the detached views get reattached.

This might have something to do with how exactly the UI is closed (close button vs. Ctrl/Cmd+W vs. Cmd+Q) or what window had focus when the UI was closed. I haven't found out yet what exactly causes it.

**Comment by dgelessus** [comment]
I can't reproduce this anymore... we can probably close this in a week or two if it doesn't happen again.

It's possible that this happens when holding down Ctrl/Cmd+W for too long. If the UI takes long enough to close, the held down key combination could repeat, which could close another window after the main window is already closed. I couldn't reproduce this though (the UI closes too quickly on my machine).

**Comment by favu100** [comment]
Close issue as it cannot be reproduced. Reopen if it appears again
