### ISSUE TITLE
Fix Internationalized Strings for Checking Types in Symbolic Model Checking, Symbolic Animation, Test Case Generation and SimB

### ISSUE THREAD

**Issue by favu100** [hhu-stups/prob-issues#51]
Strings for checking types in Symbolic Model Checking, Symbolic Animation, Test Case Generation, and SimB are not internationalized yet

**Comment by iTitus** [comment]
~~Is this fixed @favu100 ?~~
answer: no

**Comment by iTitus** [comment]
- [x] `SymbolicCheckingType`
- [x] `SymbolicAnimationType`
- [x] `SimulationType`
- [x] `TestCaseGenerationType`
