### ISSUE TITLE
shift key is not woeking in PRO-B  WINDOWS 10 x86

### ISSUE THREAD

**Issue by djourang** [hhu-stups/prob-issues#55]
i can not use the shift key , by this fact i can not put so many character like & # ....

**Comment by djourang** [comment]
It's not confortable but if i Install dutch keybor and open the Virtual keyboard, it help a little by using (maj) and (altGr) keys

**Comment by dgelessus** [comment]
Thank you for the bug report. I think this is a duplicate of #54.

Until this is fixed, probably the easiest workaround is to use an external text editor instead of the built-in one.
