### ISSUE TITLE
Model Checking Table View does not update

### ISSUE THREAD

**Issue by favu100** [hhu-stups/prob-issues#58]
Sometimes, the model checking item does not appear in the table after applying a model checking task. When switching a machine, or the project, the item appears. It seems that, the table is not refreshed correctly.

**Comment by dgelessus** [comment]
Fixed by @favu100 in hhu-stups/prob2_ui@1ac7e4bf3a3c335cd01e8d138ba4c137306a9f28, hhu-stups/prob2_ui@bbed142550a86dfb9e1109776b2015e75b1da97b, and hhu-stups/prob2_ui@d8bbee0b79e277ef0c975adb202fe0bfcd009f3b.
