### ISSUE TITLE
QoL: Adding numerous words to the Syntax Higlighting of ProB2UI

### ISSUE THREAD

**Issue by SeeBasTStick** [hhu-stups/prob-issues#67]
While working with an Event-B file some words are not highlighted making it harder to read the code:

* AXIOMS
* THEOREMS
* EVENT

**Comment by dgelessus** [comment]
This is related to the larger issue that the editor highlights Event-B code using the *classical* B parser. Because of the syntax differences, Event-B should have its own syntax highlighting, probably using the regex-based highlighting that is also used for all other languages.
