### ISSUE TITLE
Index out of bounds in LTL view when using unknown identifier

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#69]
I accidentally typed a formula G {x<10} where the B model only has the variable xx.
I got an exceptions (see below).
<img width="644" alt="Screenshot 2021-06-10 at 15 42 32" src="https://user-images.githubusercontent.com/1742246/121535910-dfe4ef00-ca02-11eb-88a6-92f9a6d74f8e.png">
![Screenshot 2021-06-10 at 15 42 55](https://user-images.githubusercontent.com/1742246/121535929-e4a9a300-ca02-11eb-99d9-bd612ec8c684.png)

**Comment by dgelessus** [comment]
~~Looks like the same exception as reported for the B editor in #56. The fix should be the same as well.~~

**Comment by iTitus** [comment]
I fxed the bug, but the intended functionality is not restored, it has been missing since atleast 2019.
This seems to be a Prolog error/oversight.

Prolog only gives us:
```
R=typeerror
Errors='Unknown identifier "x"
 ### Line: 1, Column: 0 until 1'
```

This contains no information to find the exact location of the error, even though Prolog should have it.
The exact position of the error should be returned as numbers, then ProB2-UI/Kernel can implement better highlighting.

**Comment by iTitus** [comment]
The relevant JIRA ticket is https://probjira.atlassian.net/browse/PROB2UI-400

**Comment by dgelessus** [comment]
The Prolog side now returns LTL errors with position info. I've also updated the ProB 2 API and UI to handle the new position info.

There is still the issue (that we already discussed) where semantic errors inside embedded B formulas have incorrect error positions (they are returned relative to the start of the embedded B formula, not the start of the whole LTL formula).

**Comment by leuschel** [comment]
The position infos need probably to be fixed in the Java LTL parser.
Currently Prolog gets for the formula
  G {x>1} 
the term:
globally(ap(bpred(greater(pos(-1,-1,1,1,1,4),identifier(pos(-1,-1,1,1,1,2),x),integer(pos(-1,-1,1,3,1,4),1)))))

**Comment by dgelessus** [comment]
(forgot to mention this issue in the commit message) hhu-stups/probparsers@1efddf8317830bb46bb660708df1570b16d02d5b allows overriding the starting line/column number for the parser input, without having to add artificial whitespace (which broke multiple tests). The LTL parser now uses this to add correct positions to nested B formulas.
