### ISSUE TITLE
Separate Model Checking in ProB2-UI

### ISSUE THREAD

**Issue by favu100** [hhu-stups/prob-issues#71]
Separate Model Checking into Errors (Invariant, Deadlock, ...) and Goal (Separated into GOAL from Definitions and Goal from TextField)

**Comment by leuschel** [comment]
The Find Goal dialog should have the option of
 [x] use GOAL from DEFINITIONS     (enabled if such a definition exists)
 [ ] custom goal  ___________________________________

(Note: that option 1 corresponds to typing GOAL into the second option.)
The custom goal could maybe allow LTL/CTL atomic properties  (e(Op), deadlock(Op1,...,Opk),...).
Alternatively we could have a dialog to allow selecting events which are to be enabled.

The dialog box should have the option of selecting the search (DF, BF, Mixed).
We could add the option of starting the search from the current state; but this would currently require using the CTL model checker (meaning we have DF search) or the LTL model checker (and we have BF search).
The regular model checker cannot be easily instructed to start from the current state (except with the REFOCUS command in Tcl/Tk, which modifies the state space).

**Comment by SherinSchneider** [comment]
ModelcheckingStage has now been rearranged
