### ISSUE TITLE
IndexOutOfBoundsException in LTL Editor

### ISSUE THREAD

**Issue by favu100** [hhu-stups/prob-issues#79]
IndexOutOfBOundsException occurs when applying LTL Model Checking via the LTL Editor with the formula:

G([move_up] => {cur_floor = cur_floor$0 + 1})

for the Lift model

**Comment by iTitus** [comment]
I get this error: `Primed version "cur_floor$0" of identifier cur_floor not available`. Is this still relevant?

**Comment by leuschel** [comment]
Yes, I thinks this error message is correct.
What should work with the new LTL parser though is
```G([move_up] => BA({cur_floor = cur_floor $0 + 1}))```

**Comment by iTitus** [comment]
Nice, this LTL formula does not crash anymore.
So this can be closed I think.
