### ISSUE TITLE
WD Optimization causes a cut-away of solutions in the Animator

### ISSUE THREAD

**Issue by SeeBasTStick** [hhu-stups/prob-issues#82]
In commit:
https://gitlab.cs.uni-duesseldorf.de/stups/prob/prob_prolog/-/commit/4eef403de56cfe236627a2ab88218ca6e16557d2
a WD optimization was introduced for implications, where the left-hand side is removed in the case of a let expression.  Unfortunately, this also removes valid solutions. For example, here:
```
set_cars = ANY new_value WHERE  new_value : BOOL & new_value = TRUE => peds_go = FALSE
                        THEN
                            cars_go := new_value
                        END
```
Where the left-hand side is needed to determine the actual value used in the body, the animator can no longer calculate all valid solutions for some states (new_value always has the same value).
This results in failing tests in the Java Kernel.

**Comment by dgelessus** [comment]
I think this is fixed with prob_prolog commit [ec28233f](https://gitlab.cs.uni-duesseldorf.de/stups/prob/prob_prolog/-/commit/ec28233f71dd00dcf3a70313014832062931c711). At least the CI for ProB 2 now runs without errors again.
