### ISSUE TITLE
Sequentiel Substitution seems to be incrorrect

### ISSUE THREAD

**Issue by SeeBasTStick** [hhu-stups/prob-issues#83]
The sequential substitution seems to be not correctly parsed. Consider the following example:

```
MACHINE MachineB

VARIABLES y, x

INVARIANT y : NAT & x : NAT

INITIALISATION y := 0 ; x := NAT

OPERATIONS 
 Foo =  BEGIN y := 4 ; y := 3 END;
 FooBar =  y := 4 || x := 3 ; 
 Bar =  y := 4 ; x := 3 
END
```

I get the error message:
```[13,21] expecting: '(', dot, equal, identifier literal``` , which points to the last line in the operations.
I assume that the parser always expects a new operation after an ```;``` which is not always correct.

**Comment by leuschel** [comment]
You need to put BEGIN END or ( ) around ; and || in our parser.

See for example:
https://prob.hhu.de/w/index.php?title=Current_Limitations

**Comment by leuschel** [comment]
However, it seems that BEGIN END is not required around the parallel composition.

**Comment by leuschel** [comment]
This machine can be parsed:

```
MACHINE ParserTest 

VARIABLES y, x

INVARIANT y : NAT & x : NAT

INITIALISATION  y := 0 ; x :: NAT 

OPERATIONS 
 Foo =  BEGIN y := 4 ; y := 3 END;
 FooBar =  y := 4 || x := 3 ; 
 Bar = BEGIN y := 4 ; x := 3 END
END
```
Strangely the BEGIN END is also not needed in the initialisation.

**Comment by SeeBasTStick** [comment]
Okay, thanks for the heads up. The thing that bothered me was that it is allowed in the initialisation, which makes me think the problem is "simply" in distinguishing operations properly. As it works as intended, I will close the issue.

**Comment by leuschel** [comment]
It is still a bit strange that it is accepted for the initialisation. We may re-investigate this issue at some later point.
