### ISSUE TITLE
ProB2-UI does not display partial_setup_constants

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#90]
ProB can generate a $partial_setup_constants (PARTIAL_SETUP_CONSTANTS) transition when not all PROPERTIES/axioms were checked.
This can happen e.g. due to an inconsistency which did not prevent all constants from being valued, or when prob-ignore pragams are used.
These transitions are not shown in the ProB2-UI operations view, and the user is led to believe there is a deadlock.

An example model to reproduce this is
```
MACHINE IgnorePragmaTest3
DEFINITIONS SET_PREF_USE_IGNORE_PRAGMAS == TRUE
SETS
 ID={aa,bb}
CONSTANTS x,y,z
PROPERTIES
 x : INTEGER &
 y : NATURAL &
 x : {200,201} &
 y = x+x &
 x > y /*@desc prob-ignore */ &
 !zz.(zz>y => y mod zz = y) /*@desc prob-ignore */ &
 z>22 & z<24
END
```

**Comment by leuschel** [comment]
![Screenshot 2021-10-07 at 08 29 31](https://user-images.githubusercontent.com/1742246/136331285-7b9e236e-9904-449c-a035-e7e2b242a749.png)

**Comment by leuschel** [comment]
When running from source, I do not have this issue.
I just realised that the latest SNAPSHOT is from 24/9.

**Comment by dgelessus** [comment]
I just manually started a new CI build, so in a few minutes there should be a new ProB 2 UI snapshot with the new CLI.
