### ISSUE TITLE
ProB2UI State View Value details too short

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/prob-issues#93]
When double clicking on a value, e.g., a large set the same shortened version of the value is shown.

It would probably make sense to set MAX_DISPLAY_SET to -1 or to a large value so that the user can inspect the full value.

Also, even when one manually sets MAX_DISPLAY_SET to a larger value, the string in the dialog is truncated.

**Comment by leuschel** [comment]
Probably we need to call bvisual2:bv_get_value_unlimited when double clicking on a value.
The bvisual2 / prob2_interface code currently has a limit of 600 for pretty printing the values
```
value_post_processing2(btvalue(BValue,Expr),v(Value)) :-
    (get_unlimited_value -> translate_bvalue_for_expression(BValue,Expr,Value)
     ; translate_bvalue_for_expression_with_limit(BValue,Expr,600,Value) % one can always use bv_get_value_unlimited
    ).
 ```
This makes sense for values shown in a column, but not for values shown in a dialog.

**Comment by Inab1993** [comment]
added a checkbox in the detailview that sets the max_display_set-preference temporary to -1, to show the full (or at least a larger display) of the value, but is still limited to 600 chars currently

**Comment by iTitus** [comment]
Fixed in dev, need a Prolog & Kernel release to use it in the UI
